baseurl = "http://example.com/"
languageCode = "en-us"
title = "Material Design Lite Portfolio Theme"
theme = "mdl-portfolio"

[params]

    [params.head]
        description = "Turing Portfolio"
        title = "Alan Turing"

        [params.head.style]
            primary = "red"
            accent = "teal"

    # replace headshot.jpg under static/img with your own image
    [params.header]
        title = "Alan Turing"
        subtitle = "Computer Scientist - Mathematician - Logician - Cryptanalyst"

        [params.header.nav]
            portfolio = "Portfolio"
            blog = "Blog"
            about = "About"
            contact = "Contact"

    [params.social]
        twitter = "myusername"
        google = "myusername"
        facebook = "myusername"
        github = "myusername"
        instagram = "myusername"
        linkedIn = "myusername"
        stackoverflow = "myusername"
        email = "adalovelace@gmail.com"
        resume = "resume.html"

    [params.ga]
        id = "UA-XXXXXXXX-1"
